import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";


export const metadata = {
  title: "Firebase & Realtime",
  description: "Generated by firebase & Realtime",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <AuthProvider> {children}</AuthProvider>
      </body>
    </html>
  );
}
